### ISSUE TITLE
issue with running pytest fixtures

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-cutter#10]
[Reported by](https://github.com/chrisjsewell) by @chrisjsewell

Ok getting somewhere; https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/419795868, I get:

```python
FixtureError: 'AiiDA dbenv can not be loaded while creating a test profile'
```

**Comment by ltalirz** [comment]
@DropD Could you please have a look at the travis log? this is pytest...

**Comment by chrisjsewell** [comment]
Ok sorted: https://travis-ci.org/chrisjsewell/aiida-crystal17/builds/420026369
The code in the `test.test_calculation.aiida_profile` function needed rewriting, and a `reentry scan` was required.
Also, for your consideration, if you look at my `.travis.yaml`, I've setup a separate `pre-commit` test environment, like `aiida-quantumespresso` does,  which also has a seperate docs one:

```shell
        # Compile the docs (HTML format); -W to convert warnings in errors, 
        # -n to warn about all missing references
        SPHINXOPTS="-nW" make -C docs html
```

**Comment by chrisjsewell** [comment]
It also makes sense to split the session scoped test fixture into an overarching conftest.py, 
 as per https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions 

(https://travis-ci.org/chrisjsewell/aiida-crystal17/builds/420040671)

**Comment by ltalirz** [comment]
> Ok sorted: https://travis-ci.org/chrisjsewell/aiida-crystal17/builds/420026369

Great! And sorry for the trial-and-error process - once the plugin cutter has been used a bit more, I hope it will make the plugin development experience more smooth.

> Also, for your consideration, if you look at my `.travis.yaml`, I've setup a separate `pre-commit` test environment, like `aiida-quantumespresso` does,  which also has a seperate docs one

Yes, this also happens in the [aiida plugin cutter](https://github.com/aiidateam/aiida-plugin-cutter/blob/master/.travis.yml) but I didn't add it to the generate plugin yet because it is adding complexity.
On the other hand, one could assume that people, who activate travis, may be a bit more advanced...

Adding a `docs` test seems reasonable to me, `pre-commit` would seem a bit too harsh, since we don't force people to use our coding style. What do you think?

**Comment by chrisjsewell** [comment]
Obviously the version check part of `pre-commit` needs to pass, but then maybe `allow_failures` on the the lint testing?

**Comment by ltalirz** [comment]
@chrisjsewell I've never really used pytest, but if you would be willing to make a PR to [aiida-diff](https://github.com/ltalirz/aiida-diff) that replaces unittest by pytest, I would be very happy to include this in the plugin cutter.

We could be very fancy and ask about `unittest` vs `pytest` in the cookiecutter recipe...

**Comment by chrisjsewell** [comment]
Yeh I'm sure I can do that (maybe not today though!), as I think `pytest` has some advantages over `unittest`

**Comment by ltalirz** [comment]
docs test added in pr #16 (pre-commit is run as well, but allowed to fail).
I'm closing this, please continue discussion related to adding pytest example in #9
