### ISSUE TITLE
fix aiida-diff docs

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-cutter#102]
see https://github.com/aiidateam/aiida-plugin-cutter/pull/101#issuecomment-1913670610

**Comment by unkcpz** [comment]
Why the `load_profile` was required in the first place? I guess it is safe to just remove it? 

For the aiidalab app cookiecutter, we plan to move to using `mkdoc` with `mkdoc-materials` theme, it is easy to start and also support some fancy feature as sphnix. We can consider it for the aiida plugin cutter as well.
