### ISSUE TITLE
test computer not configured for user

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-cutter#12]
When doing `verdi run examples/submit.py`, calculations end up with `SUBMISSIONFAILED` because of
```
|   Submission of calc 914 failed, computer pk= 2 (localhost-test) is not configured for aiidauser leopold.talirz@epfl.ch
```

Need to figure out how to configure the computer programmatically.
For the moment, a workaround is to `verdi run examples/submit.py` once to set up the computer, and then
```
verdi computer configure localhost-test
```

**Comment by chrisjsewell** [comment]
Hey @ltalirz, yes I came across the same issue.

I have modified your `get_computer` function to include a configuration option:
https://github.com/chrisjsewell/aiida-crystal17/blob/20b22cd6dc5fc46597928444a860029fea119f9c/aiida_crystal17/tests/__init__.py#L70

For aiida_core-1.0, you can simply use `aiida.control.computer.configure_computer` (which wrks in testing for django and sqlalchemy: https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/426840055) 

But, for v0.12, this isn't available, so I've ripped out some of the code from `aiida_core.aiida.cmdline.commands.computer.Computer.computer_configure` (https://github.com/chrisjsewell/aiida-crystal17/blob/20b22cd6dc5fc46597928444a860029fea119f9c/aiida_crystal17/tests/__init__.py#L115).
This works for django, but for sqlalchemy `session = get_scoped_session()` returns `None` (at least on travis), so I don't know if you know of any quick fix?

**Comment by chrisjsewell** [comment]
A related problem (again only for v0.12 and not v1.0), is that submission to a local computer (such as the one created for the tests) appear to hang in the `TOSUBMIT` state.

For example:

```python
import os
from aiida.orm import Code
from aiida.work.run import run
import aiida_crystal17.tests as tests
from aiida.orm.data.singlefile import SinglefileData

code = Code.get_from_string('crystal17.basic-mock_runcry17@localhost-test')
process = calc.process()

infile = SinglefileData(
    file=os.path.join(tests.TEST_DIR, "input_files",
                      'mgo_sto3g_scf.crystal.d12'))
inputs_dict = {
    "_options": {"resources": {"num_machines": 1, "num_mpiprocs_per_machine": 1},
                 "withmpi": False,
                 "max_wallclock_seconds": 30},
    "input_file": infile,
    "code": code
}

output, pid = run(process, _return_pid=True, **inputs_dict)
```

Hangs on:

```console
>>> verdi calculation list 2480
# Last daemon state_updater check: 2D:05h:50m ago (at 09:49:20 on 2018-09-07)
  PK  Creation    State       Sched. state  Computer        Type
----  ----------  --------  --------------  --------------  ---------------
2480  58m ago     TOSUBMIT                  localhost-test  crystal17.basic

```

Any advice, or should I maybe raise it on the main repo?

**Comment by chrisjsewell** [comment]
@DropD I was just having a look through the `aiida-vasp` code (and borrowing some of your approaches thanks :) ). You haven't come across any similar issues as mine one above?

I notice that in `test_base_wf.py` you have a `create_authinfo` function, but if I use this for SQLA, I get:

```
InvalidRequestError: When initializing mapper Mapper|DbAuthInfo|db_dbauthinfo, expression 'DbUser' failed to locate a name ("name 'DbUser' is not defined"). If this is a class name, consider adding this relationship() to the <class 'aiida.backends.sqlalchemy.models.authinfo.DbAuthInfo'> class after both dependent classes have been defined.
```

(see https://travis-ci.org/chrisjsewell/aiida-crystal17/jobs/426942030)

Also I see below that (in `test_base`), you are skipping a test for versions<1.0 to do with running processed I think.

Sorry, one more question: In your tests you have a `get_process_inputs` fixture, yet when I search the repo, it's not actually there. Is this imported in from somewhere?

**Comment by ltalirz** [comment]
Thanks for your suggestions on `get_computer` - that's definitely more code than I would have hoped to need to add to the plugin for this.  @giovannipizzi is there a simpler way to achieve this?

> Any advice, or should I maybe raise it on the main repo?

I think this may be a good issue for the `aiida-core` repo

Re `aiida-vasp`: Indeed we figured out at some point that, due to a bug in the test fixtures, the tests were never running for the `sqla` backend. This may explain what you found.
@DropD has moved on to another job, so he might take some time to respond

**Comment by chrisjsewell** [comment]
Thanks @ltalirz. Yeh obviously I'm hoping a stable v1.0 is just around the corner, so don't want to mess around with v0.12 issues too much :)

**Comment by giovannipizzi** [comment]
@ltalirz I'm not sure we provide a simpler way to "get_or_create" a computer.
We might want to add it, but I think it's useful only in the tests, right?

**Comment by ltalirz** [comment]
in aiida 1.0.0, this is now solved simply by `computer.configure()`
