### ISSUE TITLE
travis pre-commit tests shouldn't include yapf

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-plugin-cutter#24]
It fails just because the files are different

**Comment by ltalirz** [comment]
sorry, could you please be a bit more specific (and possibly include a link to a travis build?)

**Comment by chrisjsewell** [comment]
This is an example: https://travis-ci.org/aiidateam/aiida-plugin-cutter/jobs/421506134.
I don't think you can't actually run `yapf` on the `aiida-plugin-cutter` repo anyway, because you get this:

```python
    import {{cookiecutter.module_name}}  # pylint: disable=wrong-import-position
           ^
SyntaxError: invalid syntax
```

Surely you only need `prospector` to actually check the code style, and `yapf` is just a formatter to help pass the `prospector` test. For instance I'm using PyCharm, which already runs all the formatting, so I don't need `yapf`

**Comment by chrisjsewell** [comment]
Ok yeh fair enough. the only annoyanceI had (unless you know of another way) is that, to pass the tests for changes to this actual repo you have to run:

```shell
cookiecutter --no-input -f .
cd aiida-diff/
yapf --diff --recursive .
```

Then manually got through and fix all the diffs

**Comment by ltalirz** [comment]
That is a fair point. Hm... maybe the solution is to run yapf as part of the cookiecutter recipe.

**Comment by ltalirz** [comment]
just realized this wasn't fixed because I forgot to install yapf in travis. will be fixed in a minute
