### ISSUE TITLE
add test for parser class 

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-cutter#5]

**Comment by ltalirz** [comment]
Taken care of in a sense by `test_process`, but I'd still like to add an explicit test of the parser as in
https://github.com/ltalirz/aiida-zeopp/blob/942b0ac4e522f66583fb8d49fabc3c61bd5320e7/aiida_zeopp/parsers/test_network.py#L11

**Comment by dev-zero** [comment]
are you sure about that? I tried to port the aiida-cp2k plugin to this new testing infrastructure and I don't get output nodes parsing since the daemon does not run (with almost latest AiiDA develop/HEAD)

**Comment by ltalirz** [comment]
@dev-zero works now https://github.com/aiidateam/aiida-diff/blob/master/aiida_diff/tests/test_calculations.py#L58

I'm going to close this since this is part of a larger discussion of how to test parsers separately that needs to be had in general (and won't be addressed in the plugin cutter)
