### ISSUE TITLE
add instructions for running tests & examples to README

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-plugin-cutter#7]

**Comment by chrisjsewell** [comment]
Something to maybe add in the instructions:
One 'issue' I've just come across is that, if you change/update the `setup.json`s `entry-points`, this will break the tests. `pip install -U -e .` fixed this, but I don't know if there is a better way?

**Comment by chrisjsewell** [comment]
@ltalirz is there a 'simple' way to alter the [`test_submit`](https://github.com/aiidateam/aiida-plugin-cutter/blob/master/%7B%7Bcookiecutter.plugin_name%7D%7D/%7B%7Bcookiecutter.module_name%7D%7D/tests/test_calculations.py) function, to test if the calculation succeeds (and its outputs)?

I was looking at the [`to-context` workchain example](https://aiida-core.readthedocs.io/en/latest/concepts/workflows.html#to-context), but I couldn't see an obvious way of returning the *future* of the calculation submission.

**Comment by ltalirz** [comment]
@chrisjsewell My latest state is what you have discovered as well - for workchains yes, for calculations no.
Mentionin @sphuber in case he has any hints on this.

**Comment by chrisjsewell** [comment]
No this is only locally, so not a massive issue.

**Comment by ltalirz** [comment]
Have you tried running `reentry scan -r aiida` in between these changes?

**Comment by ltalirz** [comment]
Original issue #7 addressed PR #13.

**Comment by ltalirz** [comment]
Closing this as original issue resolved. 

> One 'issue' I've just come across is that, if you change/update the `setup.json`s `entry-points`, this will break the tests. `pip install -U -e .` fixed this, but I don't know if there is a better way?

Does running `reentry scan -r aiida` in between these changes solve the problem?
