### ISSUE TITLE
Voluptuous Dependency

### ISSUE THREAD

**Issue by HaoZeke** [aiidateam/aiida-plugin-cutter#84]
It seems that `voluptuous` is veering towards being deprecated outright. Might consider updating to [schema](https://github.com/keleshev/schema) (which seems similar) or even [pydantic](https://pydantic-docs.helpmanual.io/) (might be more work).

Not really an issue for new plugins of course.

**Comment by ltalirz** [comment]
Thanks for the suggestion - if indeed voluptuous maintenance will stop altogether [1] and there is a good alternative, I'm happy to accept a PR to switch.

What I like about voluptuous is ist minimalistic, yet very expressive design.
I've used pydantic as well but there one would end up writing a lot more code. Haven't looked at schema yet.

[1] What evidence are you basing this on? I had a look at the repo and I agree that the developer seems a bit slow in responding to requests but there has certainly still been activity in 2021.

**Comment by HaoZeke** [comment]
I was a little concerned about the contributions only aspect it was running on. I haven't seen that model be very successful in the past, and have mostly learned to migrate away, but yeah a closer look at the repo makes it clear that it seems to be going alright for now.
