### ISSUE TITLE
yapf -> black

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-plugin-cutter#85]
black rules, yapf drools

**Comment by ltalirz** [comment]
feel free to change, I have no strong feelings about this

**Comment by chrisjsewell** [comment]
Plus adding some more pre-commit hooks like in https://github.com/aiidateam/aiida-firecrest/blob/main/.pre-commit-config.yaml

**Comment by chrisjsewell** [comment]
it would also be ideal not to have to use pylint with `language: system`, which does not play nicely with pre-commit.ci an github desktop, etc. theres some talk of how to sync dependencies here, but unfortunately no current, complete soltuion: https://github.com/pre-commit/pre-commit/issues/945

**Comment by ltalirz** [comment]
I noticed a CI autoupdate PR (maybe on this plugin, don't remember) but the checks were failing.
I think having to deal with another monthly PR that updates dependencies for each plugin may be more hassle than adding value.

But we can certainly add some other linters and hooks that we feel are useful.

As for the `language: system` I agree it's not ideal but until there is an all-around better solution I would wait to switch.

**Comment by chrisjsewell** [comment]
> I recently noticed a CI autoupdate PR somewhere
> I think having to deal with another monthly PR that updates dependencies for each plugin may be more hassle than adding value.

Oh I very much disagree, I've already added https://pre-commit.ci/ to aiida-core and other aiidateam packages, and we use it in basically every EBP package.
Its great, because otherwise these hook versions gradually get very out of date, and it usually only takes a few seconds to merge 

You can also configure the autoupdate frequency etc: https://pre-commit.ci/#configuration

**Comment by ltalirz** [comment]
done in https://github.com/aiidateam/aiida-plugin-cutter/pull/88
